#!/usr/bin/python3
import sys
from math import *

def calc_one():
    nb1 = int(sys.argv[1])
    nb2 = int(sys.argv[2])
    nb = 0.0
    i = 0
    tab = []
    while (i <= 200):
        nb = (1 / (float(nb2) * sqrt(2 * pi))) * exp(-0.5 * pow((float(i) - float(nb1)) / float(nb2), 2))
        tab.append(nb * 100)
        if (tab[i] < 0):
            exit(84)
        print("%d %0.5f" %(i, nb))
        i+=1

def calc_two():
    nb1 = int(sys.argv[1])
    nb2 = int(sys.argv[2])
    i = 0.0
    nb = 0.0
    nb3 = int(sys.argv[3])
    while (i < nb3):
        nb += (1 / (float(nb2) * sqrt(2 * pi))) * exp(-0.5 * pow((float(i) - float(nb1)) / float(nb2), 2))
        i+=0.01
    print("%0.1f%% of people have a IQ inferior to %d" %(nb, nb3))
    exit(0)

def calc_three():
    nb1 = int(sys.argv[1])
    nb2 = int(sys.argv[2])
    nb3 = int(sys.argv[3])
    nb = nb3 * 1.0
    nb4 = int(sys.argv[4])
    i = 0.0
    while (nb < nb4):
        i += (1 / (float(nb2) * sqrt(2 * pi))) * exp(-0.5 * pow((float(nb) - float(nb1)) / float(nb2), 2))
        nb+=0.01
    print("%0.1f%% of people have a IQ between %d and %d" %(i, nb3, nb4))
    exit(0)

def do_all():
    if (len(sys.argv) == 3):
        calc_one()
    if (len(sys.argv) == 4):
        calc_two()
    if (len(sys.argv) == 5):
        calc_three() 

def help():
    exit(0)

def check_error():
    if (sys.argv[1] == "-h"):
        help()
    if (len(sys.argv) < 3 or len(sys.argv) > 5):
        exit(84)
    if (len(sys.argv) == 3):
        try:
            nb1 = int(sys.argv[1])
            nb2 = int(sys.argv[2])
        except:
            exit(84)
        if (nb1 < 0 or nb2 <= 0):
            exit(84)
    if (len(sys.argv) == 4):
        try:
            nb1 = int(sys.argv[1])
            nb2 = int(sys.argv[2])
            nb3 = int(sys.argv[3])
        except:
            exit(84)
        if (nb1 < 0 or nb2 <= 0):
            exit(84)
        if (nb3 < 0 or nb3 > 200):
            exit (84)
    if (len(sys.argv) == 5):
        try:
            nb1 = int(sys.argv[1])
            nb2 = int(sys.argv[2])
            nb3 = int(sys.argv[3])
            nb4 = int(sys.argv[4])
        except:
            exit(84)
        if (nb1 < 0 or nb2 <= 0):
            exit(84)
        if (nb3 < 0 or nb3 > 200):
            exit (84)
        if (nb4 < 0 or nb4 > 200):
            exit (84)
        if (nb3 > nb4):
            exit (84)

def main():
    if (len(sys.argv) < 2):
        exit(84)
    check_error()
    do_all()

if __name__ == '__main__':
    main()